services:
  - type: web
    name: breathing-practice-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /ping
    envVars:
      - key: BOT_TOKEN
        value: 8131277180:AAFua4Um2wGYbWEUh8JlJ7s6I3vgzmIHNJM
      - key: ADMIN_ID
        value: 1389064275
      - key: APP_URL
        value: https://breathing-practice-bot.onrender.com
    autoDeploy: true