services:
  - type: web
    name: breathing-practice-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /ping
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: APP_URL
        value: https://breathing-practice-bot.onrender.com
    autoDeploy: true
