services:
  - type: web
    name: breathing-practice-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /ping
    healthCheckTimeout: 5
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: APP_URL
        value: https://breathing-practice-bot.onrender.com
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_MODE
        value: "true"
      - key: PORT
        value: "3000"
    autoDeploy: false
